import React,{createContext,useContext,useEffect,useMemo,useState} from 'react';
import {draftsRepository} from '@/lib/database';
import type {ActivityType,ContactRole,Furnishing,PropertyType} from '@/types/domain';

export type Language='ar'|'en';
const ar={
home:'الرئيسية',contacts:'الأشخاص',properties:'العقارات',matches:'المطابقات',more:'المزيد',search:'ابحث عن عقار أو شخص',welcome:'نظّم عميلك، طابق طلبه، وشارك العقار بسرعة.',
addContact:'إضافة شخص',addProperty:'إضافة عقار',importContacts:'استيراد من الهاتف',noContacts:'لا يوجد أشخاص مسجلون',noProperties:'لا توجد عقارات مسجلة',noMatches:'لا توجد مطابقات مؤهلة حاليًا',
save:'حفظ',cancel:'إلغاء',name:'الاسم',phone:'رقم الهاتف',role:'التصنيف',notes:'ملاحظات',area:'المنطقة',rent:'الإيجار الشهري',type:'نوع العقار',bedrooms:'عدد الغرف',bathrooms:'عدد الحمامات',description:'الوصف المرسل',privateNotes:'ملاحظات خاصة لا تُرسل',paci:'الرقم الآلي PACI (اختياري)',map:'رابط الموقع',available:'متاح',rented:'مؤجر',paused:'متوقف',
language:'اللغة',dataProtection:'حماية البيانات',backupCreate:'إنشاء ومشاركة نسخة احتياطية',backupRestore:'استعادة نسخة احتياطية',backupWarningTitle:'تنبيه مهم قبل النسخ الاحتياطي',backupWarning:'هذه النسخة تحفظ بيانات الأشخاص والعقارات والطلبات فقط. ملفات الصور والفيديو غير مشمولة حاليًا. احتفظ بنسخة مستقلة منها قبل المتابعة.',continueBackup:'متابعة وإنشاء النسخة',backupFailed:'تعذر إنشاء النسخة',tryAgain:'حاول مرة أخرى.',restoreDone:'تمت الاستعادة',restoreDoneMessage:'تم دمج البيانات الموجودة في النسخة بأمان.',restoreFailed:'تعذرت الاستعادة',restoreFailedMessage:'الملف غير صالح أو غير متوافق.',privacyInfo:'بياناتك محفوظة محليًا على هاتفك ولا تتم مشاركتها إلا باختيارك. النسخة الحالية تحفظ السجلات النصية؛ احتفظ بنسخة مستقلة من الصور والفيديوهات المهمة.',
addPersonQuestion:'كيف تريد إضافة الشخص؟',fastestMethod:'اختر الطريقة الأسرع لك الآن',manualAdd:'إضافة يدويًا',manualAddHint:'اكتب الاسم والرقم والتصنيف',importHint:'اختر شخصًا أو عدة أشخاص من جهات الاتصال',importNoneSelected:'لا يوجد أي شخص محدد افتراضيًا. حدّد من تريد فقط.',phoneContactsSearch:'ابحث داخل جهات اتصال الهاتف',contactSearch:'ابحث بالاسم أو الرقم',deviceContactNotes:'ملاحظات جهة الاتصال',noImportableContacts:'لا توجد جهات اتصال مطابقة قابلة للاستيراد',alreadyExists:'موجود بالفعل — اضغط لفتح السجل',importSelected:'استيراد المحدد',permissionRequired:'الصلاحية مطلوبة',permissionContacts:'يمكنك إضافة الأشخاص يدويًا.',importDone:'تم الاستيراد',peopleImported:'تم استيراد {count} شخص.',
importRole:'تصنيف الأشخاص المستوردين',defaultImportRole:'الدور الافتراضي للدفعة',rowRole:'دور هذا الشخص',applyRoleToSelected:'تطبيق الدور الافتراضي على المحدد',replaceRoleOverridesTitle:'إعادة تعيين الأدوار الفردية؟',replaceRoleOverridesMessage:'سيتم استبدال الأدوار الفردية للصفوف المحددة بالدور الافتراضي الحالي.',applyNow:'تطبيق',selectVisible:'تحديد الظاهر',clearVisible:'إلغاء تحديد الظاهر',clearAll:'إلغاء تحديد الكل',selectedExecutable:'المحدد {selected} من {available} القابل للاستيراد',noUsablePhones:'لا يوجد رقم صالح قابل للاستيراد',invalidPhonesHere:'أرقام غير صالحة: {count}',duplicatePhonesHere:'أرقام مكررة داخل الشخص: {count}',storedNumberConflict:'هذا الرقم مسجل لدى {name}',openStoredPerson:'فتح الشخص الموجود',batchNumberConflict:'رقم مشترك داخل الدفعة — اختر صاحبه',assignNumberHere:'تعيين الرقم لهذا الشخص',numberAssignedHere:'تم تعيين الرقم لهذا الشخص',preparingContacts:'جارٍ تجهيز جهات الاتصال…',importingContacts:'جارٍ استيراد الصفوف السليمة…',importTechnicalFailure:'فشل تقني أثناء الكتابة؛ تم التراجع عن الدفعة بالكامل.',importSummaryPeople:'تم استيراد {count} أشخاص.',importSummaryPhones:'تم حفظ {count} أرقام.',importSummaryProblems:'توجد {count} مشكلة تحتاج مراجعة.',showDetails:'عرض التفاصيل',hideDetails:'إخفاء التفاصيل',finish:'إنهاء',invalidDetail:'أرقام غير صالحة: {count}',duplicateDetail:'تكرارات داخل الشخص: {count}',storedConflictDetail:'تعارضات مع أشخاص مسجلين: {count}',batchConflictDetail:'أرقام مستبعدة بسبب تعارض الدفعة: {count}',unselectedInfo:'صفوف لم يتم تحديدها: {count}',
addManualPerson:'إضافة شخص يدويًا',editPerson:'تعديل الشخص',incompleteData:'بيانات غير مكتملة',validKuwaitPhone:'اكتب الاسم ورقم هاتف صحيح.',duplicatePhone:'رقم مسجل بالفعل',duplicatePhoneMessage:'لن ننشئ نسخة مكررة من الشخص.',openExisting:'فتح السجل الموجود',phoneNumbers:'أرقام الهاتف',addPhoneNumber:'+ إضافة رقم هاتف',phoneLabel:'تصنيف الرقم كما هو في الهاتف',primaryPhone:'الرقم الأساسي',makePrimary:'اجعله أساسيًا',removePhone:'حذف الرقم',phoneRequired:'يجب تسجيل رقم هاتف واحد على الأقل.',invalidPhoneTitle:'راجع رقم الهاتف',validInternationalPhone:'اكتب رقمًا كويتيًا من 8 أرقام أو رقمًا دوليًا يبدأ بـ + أو 00.',duplicateWithinPerson:'هذا الرقم مكرر داخل الشخص نفسه.',phoneConflictTitle:'تعارض رقم الهاتف',phoneConflictMessage:'هذا الرقم مسجل لدى {name}. لن يتم دمجه أو نقله تلقائيًا.',phoneConflictGeneric:'أحد الأرقام أصبح مرتبطًا بشخص آخر. راجع الأرقام وحاول مرة أخرى.',skipNumber:'تخطي الرقم',call:'اتصال',whatsapp:'واتساب',phoneConflictOpen:'الرقم مرتبط بشخص موجود — اضغط لفتحه',phoneImportNotes:'غير صالح: {invalid} · مكرر: {duplicates}',peopleAndPhonesImported:'تم استيراد {people} شخص و{phones} رقم هاتف.',
personDetails:'تفاصيل الشخص',loading:'جارٍ التحميل…',requested:'مطلوب',requestedHint:'طلبات هذا الشخص للبحث والمطابقة',addRequested:'+ إضافة مطلوب',noRequests:'لا توجد طلبات مسجلة بعد.',offered:'معروض',offeredHint:'عقارات وصلت إليك عن طريق هذا الشخص',addOffered:'+ إضافة عقار معروض',noOffered:'لا توجد عقارات معروضة مسجلة بعد.',editPersonData:'تعديل بيانات الشخص',flexibleBudget:'ميزانية مرنة',anyProperty:'أي عقار',anyArea:'أي منطقة',edit:'تعديل',matchNow:'مطابقة الآن',
globalSearch:'البحث الشامل',peopleCount:'الأشخاص ({count})',propertiesCount:'العقارات ({count})',noSearchResults:'لا توجد نتائج مطابقة',searchHelp:'اكتب اسم الشخص أو رقمه، أو اسم العقار أو المنطقة أو رقم القطعة أو PACI',
addRentalProperty:'إضافة عقار للإيجار',editProperty:'تعديل العقار',shortPropertyName:'اسم مختصر للعقار (اختياري)',shortPropertyExample:'مثال: شقة السالمية 12',shortPropertyHelp:'هذا اسم داخلي يساعدك على تمييز الوحدة بسرعة، وليس عنوان المنطقة.',blockNumber:'رقم القطعة',blockNumberValue:'رقم القطعة {value}',notSpecified:'غير محدد',currencyPlaceholder:'بالدينار الكويتي',sizeSqm:'المساحة م²',furnishing:'التأثيث',propertyStatus:'حالة العقار',paciNumberCount:'عدد الأرقام الآلية',activityType:'نوع النشاط',chooseActivity:'اختر نوع النشاط',locationSelected:'✓ تم اختيار الموقع — اضغط للتعديل',chooseGoogleLocation:'📍 اختر الموقع على Google Maps',addMedia:'إضافة صور أو فيديو ({count})',saveProperty:'حفظ العقار',savingProperty:'جارٍ حفظ العقار…',propertySavedTitle:'تم حفظ العقار',propertySavedMessage:'تم حفظ العقار بنجاح.',propertySavedMediaWarning:'تم حفظ العقار، لكن تعذر إرفاق {count} ملف وسائط.',propertySaveFailedTitle:'تعذر حفظ العقار',propertySaveFailedMessage:'لم تُفقد البيانات. راجع الحقول وحاول مرة أخرى.',propertySizeInvalid:'اكتب مساحة صحيحة أكبر من صفر أو اتركها فارغة.',choosePropertyLocation:'اختيار موقع العقار',locationHelp:'افتح Google Maps وحدد العقار، ثم اختر مشاركة ← نسخ الرابط، وارجع للصقه هنا.',openGoogleMaps:'فتح Google Maps',pasteMapLink:'الصق رابط Google Maps هنا',or:'أو',useCurrentLocation:'استخدام موقعي الحالي',saveLocation:'حفظ الموقع',chooseLocation:'اختر الموقع',chooseLocationMessage:'افتح Google Maps والصق رابط النقطة أو استخدم موقعك الحالي.',mapOpenFailed:'تعذر فتح Google Maps',mapOpenFailedMessage:'يمكنك لصق رابط الموقع يدويًا.',locationPermission:'اسمح بالموقع أو الصق رابط Google Maps.',propertyRequired:'اختر المنطقة واكتب الإيجار الشهري.',
chooseArea:'اختر المنطقة من مناطق الكويت',chooseAreas:'اختر منطقة أو أكثر',chooseAreaTitle:'اختر المنطقة',chooseAreasTitle:'اختر المناطق',typeFirstLetters:'اكتب أول حرفين',doneCount:'تم ({count})',noArea:'لا توجد منطقة مطابقة',
addRequirement:'إضافة مطلوب',editRequirement:'تعديل المطلوب',requirementIntro:'سجل طلب الباحث بسرعة، ثم اعرض العقارات المطابقة بنسبة 70% أو أكثر.',propertyTypeRequired:'نوع العقار *',minRent:'أقل إيجار *',maxRent:'أعلى إيجار *',requiredBedrooms:'عدد الغرف المطلوب',requiredBathrooms:'عدد الحمامات المطلوب',extraConditions:'شروط أو ملاحظات إضافية',saveAndMatch:'حفظ ومطابقة الآن',saveOnly:'حفظ فقط',personMissing:'تعذر تحديد الشخص',requirementRequired:'اختر نوع العقار والمنطقة واكتب نطاق الإيجار.',reviewRent:'راجع الإيجار',rentRangeInvalid:'يجب أن يكون أعلى إيجار مساويًا أو أكبر من أقل إيجار.',
propertyDetails:'تفاصيل العقار',propertyPreview:'معاينة العقار',safeMode:'🔒 وضع آمن: الملاحظات الخاصة ومصدر العرض مخفيان.',monthlyKwd:'{value} د.ك شهريًا',kwd:'{value} د.ك',rooms:'{value} غرف',baths:'{value} حمام',paciNumbers:'{value} أرقام آلية',playVideo:'تشغيل الفيديو {number}',videoOpenFailed:'تعذر تشغيل الفيديو',videoOpenFailedMessage:'لا يوجد تطبيق متاح لتشغيل هذا الفيديو أو أن الملف غير متاح.',shareWhatsapp:'معاينة ثم مشاركة إلى WhatsApp',matchingSeekers:'الباحثون المطابقون',privateDoNotShare:'ملاحظات خاصة — لا تُشارك',
safeSharePreview:'معاينة المشاركة الآمنة',safeShareInfo:'🔒 بيانات المالك ومصدر العرض والملاحظات الخاصة لا تدخل الرسالة إطلاقًا.',sendDescription:'إرسال الوصف',sendPaci:'إرسال الرقم الآلي PACI',sendLocation:'إرسال رابط الموقع الدقيق',messageToSend:'الرسالة التي ستُرسل',shareChooseWhatsapp:'مشاركة عبر واتساب',chooseWhatsApp:'اختر تطبيق واتساب',chooseWhatsAppHint:'حدد واتساب العادي أو واتساب بيزنس لهذه العملية.',whatsappStandard:'WhatsApp — واتساب',whatsappBusiness:'WhatsApp Business — واتساب بيزنس',whatsappUnavailable:'واتساب العادي غير مثبت أو غير متاح على هذا الهاتف.',whatsappBusinessUnavailable:'واتساب بيزنس غير مثبت أو غير متاح على هذا الهاتف.',mediaShareNote:'الصور والفيديو محفوظة على هاتفك، ويمكن إرفاقها من واتساب بعد فتح الرسالة.',shareFailed:'تعذرت المشاركة',shareFailedMessage:'حاول مرة أخرى من شاشة المعاينة.',preparingPreview:'جارٍ تجهيز المعاينة…',
qualifyingResults:'تظهر النتائج المؤهلة بنسبة {score}% أو أكثر، مع سبب كل درجة.',noQualifyingResult:'لا توجد نتيجة مؤهلة الآن. جرّب تعديل الطلب أو أضف عقارًا جديدًا.',matchingProperties:'العقارات المطابقة',matchingPeople:'الباحثون المطابقون',match:'تطابق',requirementNote:'ملاحظة الطلب: {note}',client:'عميل'
} as const;
const en:Record<keyof typeof ar,string>={
home:'Home',contacts:'People',properties:'Properties',matches:'Matches',more:'More',search:'Search for a property or person',welcome:'Organize people, match requirements, and share properties quickly.',
addContact:'Add person',addProperty:'Add property',importContacts:'Import from phone',noContacts:'No people saved',noProperties:'No properties saved',noMatches:'No qualifying matches yet',save:'Save',cancel:'Cancel',name:'Name',phone:'Phone number',role:'Role',notes:'Notes',area:'Area',rent:'Monthly rent',type:'Property type',bedrooms:'Bedrooms',bathrooms:'Bathrooms',description:'Shared description',privateNotes:'Private notes — never shared',paci:'PACI number (optional)',map:'Location link',available:'Available',rented:'Rented',paused:'Paused',
language:'Language',dataProtection:'Data protection',backupCreate:'Create and share backup',backupRestore:'Restore backup',backupWarningTitle:'Important backup warning',backupWarning:'This backup currently includes people, properties, and requirement records only. Photo and video files are not included. Keep a separate copy of them before continuing.',continueBackup:'Continue and create backup',backupFailed:'Could not create backup',tryAgain:'Please try again.',restoreDone:'Restore complete',restoreDoneMessage:'The backup records were merged safely.',restoreFailed:'Restore failed',restoreFailedMessage:'The file is invalid or incompatible.',privacyInfo:'Your data stays locally on your phone and is shared only when you choose. The current backup saves text records; keep a separate copy of important photos and videos.',
addPersonQuestion:'How would you like to add this person?',fastestMethod:'Choose the fastest method for you',manualAdd:'Add manually',manualAddHint:'Enter the name, number, and role',importHint:'Choose one or more people from phone contacts',importNoneSelected:'No one is selected by default. Select only the people you need.',phoneContactsSearch:'Search within phone contacts',contactSearch:'Search by name or number',deviceContactNotes:'Phone contact notes',noImportableContacts:'No matching contacts available to import',alreadyExists:'Already saved — tap to open the record',importSelected:'Import selected',permissionRequired:'Permission required',permissionContacts:'You can still add people manually.',importDone:'Import complete',peopleImported:'Imported {count} people.',
importRole:'Imported people classification',defaultImportRole:'Default batch role',rowRole:'Role for this person',applyRoleToSelected:'Apply default role to selected',replaceRoleOverridesTitle:'Reset individual roles?',replaceRoleOverridesMessage:'Individual roles on selected rows will be replaced by the current default role.',applyNow:'Apply',selectVisible:'Select visible',clearVisible:'Clear visible',clearAll:'Clear all',selectedExecutable:'Selected {selected} of {available} importable',noUsablePhones:'No valid phone number can be imported',invalidPhonesHere:'Invalid numbers: {count}',duplicatePhonesHere:'Duplicates within this person: {count}',storedNumberConflict:'This number belongs to {name}',openStoredPerson:'Open existing person',batchNumberConflict:'Shared number in this batch — choose its owner',assignNumberHere:'Assign number to this person',numberAssignedHere:'Number assigned to this person',preparingContacts:'Preparing contacts…',importingContacts:'Importing executable rows…',importTechnicalFailure:'A technical write failed; the complete batch was rolled back.',importSummaryPeople:'Imported {count} people.',importSummaryPhones:'Saved {count} phone numbers.',importSummaryProblems:'{count} issues need review.',showDetails:'Show details',hideDetails:'Hide details',finish:'Done',invalidDetail:'Invalid phone numbers: {count}',duplicateDetail:'Duplicates within a person: {count}',storedConflictDetail:'Conflicts with saved people: {count}',batchConflictDetail:'Numbers excluded by batch conflict: {count}',unselectedInfo:'Rows not selected: {count}',
addManualPerson:'Add person manually',editPerson:'Edit person',incompleteData:'Incomplete information',validKuwaitPhone:'Enter a name and a valid phone number.',duplicatePhone:'Number already saved',duplicatePhoneMessage:'A duplicate person will not be created.',openExisting:'Open existing record',phoneNumbers:'Phone numbers',addPhoneNumber:'+ Add phone number',phoneLabel:'Phone label as stored',primaryPhone:'Primary number',makePrimary:'Make primary',removePhone:'Remove number',phoneRequired:'At least one phone number is required.',invalidPhoneTitle:'Review phone number',validInternationalPhone:'Enter an 8-digit Kuwait number or an international number starting with + or 00.',duplicateWithinPerson:'This number is duplicated for the same person.',phoneConflictTitle:'Phone number conflict',phoneConflictMessage:'This number belongs to {name}. It will not be merged or reassigned automatically.',phoneConflictGeneric:'One of these numbers now belongs to another person. Review the numbers and try again.',skipNumber:'Skip number',call:'Call',whatsapp:'WhatsApp',phoneConflictOpen:'Number belongs to an existing person — tap to open',phoneImportNotes:'Invalid: {invalid} · Duplicates: {duplicates}',peopleAndPhonesImported:'Imported {people} people and {phones} phone numbers.',personDetails:'Person details',loading:'Loading…',requested:'Required',requestedHint:'This person’s requirements for search and matching',addRequested:'+ Add requirement',noRequests:'No requirements saved yet.',offered:'Offered',offeredHint:'Properties received through this person',addOffered:'+ Add offered property',noOffered:'No offered properties saved yet.',editPersonData:'Edit person details',flexibleBudget:'Flexible budget',anyProperty:'Any property',anyArea:'Any area',edit:'Edit',matchNow:'Match now',
globalSearch:'Global search',peopleCount:'People ({count})',propertiesCount:'Properties ({count})',noSearchResults:'No matching results',searchHelp:'Enter a person’s name or number, or a property, area, block number, or PACI',addRentalProperty:'Add rental property',editProperty:'Edit property',shortPropertyName:'Short property name (optional)',shortPropertyExample:'Example: Salmiya Apartment 12',shortPropertyHelp:'This is an internal name to identify the unit quickly, not the area address.',blockNumber:'Block number',blockNumberValue:'Block {value}',notSpecified:'Not specified',currencyPlaceholder:'Kuwaiti dinars',sizeSqm:'Area (m²)',furnishing:'Furnishing',propertyStatus:'Property status',paciNumberCount:'Number of PACI numbers',activityType:'Activity type',chooseActivity:'Choose activity type',locationSelected:'✓ Location selected — tap to edit',chooseGoogleLocation:'📍 Choose location on Google Maps',addMedia:'Add photos or video ({count})',saveProperty:'Save property',savingProperty:'Saving property…',propertySavedTitle:'Property saved',propertySavedMessage:'The property was saved successfully.',propertySavedMediaWarning:'The property was saved, but {count} media files could not be attached.',propertySaveFailedTitle:'Could not save property',propertySaveFailedMessage:'Your input was not lost. Review the fields and try again.',propertySizeInvalid:'Enter an area greater than zero or leave it empty.',choosePropertyLocation:'Choose property location',locationHelp:'Open Google Maps, select the property, choose Share → Copy link, then return and paste it here.',openGoogleMaps:'Open Google Maps',pasteMapLink:'Paste Google Maps link here',or:'Or',useCurrentLocation:'Use my current location',saveLocation:'Save location',chooseLocation:'Choose location',chooseLocationMessage:'Paste a Google Maps link or use your current location.',mapOpenFailed:'Could not open Google Maps',mapOpenFailedMessage:'You can paste the location link manually.',locationPermission:'Allow location access or paste a Google Maps link.',propertyRequired:'Choose an area and enter the monthly rent.',
chooseArea:'Choose from Kuwait areas',chooseAreas:'Choose one or more areas',chooseAreaTitle:'Choose area',chooseAreasTitle:'Choose areas',typeFirstLetters:'Type the first two letters',doneCount:'Done ({count})',noArea:'No matching area',addRequirement:'Add requirement',editRequirement:'Edit requirement',requirementIntro:'Save the requirement quickly, then view properties matching 70% or more.',propertyTypeRequired:'Property type *',minRent:'Minimum rent *',maxRent:'Maximum rent *',requiredBedrooms:'Required bedrooms',requiredBathrooms:'Required bathrooms',extraConditions:'Extra conditions or notes',saveAndMatch:'Save and match now',saveOnly:'Save only',personMissing:'Could not identify the person',requirementRequired:'Choose a property type and area, then enter the rent range.',reviewRent:'Review rent',rentRangeInvalid:'Maximum rent must be equal to or greater than minimum rent.',
propertyDetails:'Property details',propertyPreview:'Property preview',safeMode:'🔒 Safe mode: private notes and source are hidden.',monthlyKwd:'KWD {value} monthly',kwd:'KWD {value}',rooms:'{value} bedrooms',baths:'{value} bathrooms',paciNumbers:'{value} PACI numbers',playVideo:'Play video {number}',videoOpenFailed:'Could not play video',videoOpenFailedMessage:'No video player is available or the file cannot be opened.',shareWhatsapp:'Preview and share to WhatsApp',matchingSeekers:'Matching seekers',privateDoNotShare:'Private notes — never shared',safeSharePreview:'Safe share preview',safeShareInfo:'🔒 Owner details, source, and private notes are never included in the message.',sendDescription:'Include description',sendPaci:'Include PACI number',sendLocation:'Include exact location link',messageToSend:'Message to be sent',shareChooseWhatsapp:'Share through WhatsApp',chooseWhatsApp:'Choose WhatsApp app',chooseWhatsAppHint:'Choose standard WhatsApp or WhatsApp Business for this action.',whatsappStandard:'WhatsApp',whatsappBusiness:'WhatsApp Business',whatsappUnavailable:'Standard WhatsApp is not installed or is unavailable on this phone.',whatsappBusinessUnavailable:'WhatsApp Business is not installed or is unavailable on this phone.',mediaShareNote:'Photos and videos stay on your phone and can be attached in WhatsApp after opening the message.',shareFailed:'Sharing failed',shareFailedMessage:'Please try again from the preview screen.',preparingPreview:'Preparing preview…',qualifyingResults:'Results scoring {score}% or higher are shown with an explanation for every score.',noQualifyingResult:'No qualifying result yet. Edit the requirement or add another property.',matchingProperties:'Matching properties',matchingPeople:'Matching seekers',match:'Match',requirementNote:'Requirement note: {note}',client:'Client'
};
export type TranslationKey=keyof typeof ar;const dictionaries={ar,en};
const roles:Record<Language,Record<ContactRole,string>>={ar:{tenant:'باحث للإيجار',owner:'مالك',broker:'دلال',real_estate_company:'شركة عقارية',building_guard:'حارس'},en:{tenant:'Tenant',owner:'Owner',broker:'Broker',real_estate_company:'Real Estate Company',building_guard:'Building Guard'}};
const propertyTypes:Record<Language,Record<PropertyType,string>>={ar:{apartment:'شقة',villa:'فيلا',floor:'دور',building:'بناية',office:'مكتب',shop:'محل',warehouse:'مخزن',chalet:'شاليه'},en:{apartment:'Apartment',villa:'Villa',floor:'Floor',building:'Building',office:'Office',shop:'Shop',warehouse:'Warehouse',chalet:'Chalet'}};
const furnishings:Record<Language,Record<Furnishing,string>>={ar:{any:'أي',furnished:'مفروش',semi_furnished:'نصف مفروش',unfurnished:'غير مفروش'},en:{any:'Any',furnished:'Furnished',semi_furnished:'Semi-furnished',unfurnished:'Unfurnished'}};
const activities:Record<Language,Record<ActivityType,string>>={ar:{company_headquarters:'مقر شركة',educational_institute:'معهد تعليمي',health_institute:'معهد صحي',law_office:'مكتب محامي',other:'نشاط آخر'},en:{company_headquarters:'Company headquarters',educational_institute:'Educational institute',health_institute:'Health institute',law_office:'Law office',other:'Other activity'}};
export function translate(language:Language,key:TranslationKey,values:Record<string,string|number>={}):string{return Object.entries(values).reduce((text,[name,value])=>text.replaceAll(`{${name}}`,String(value)),dictionaries[language][key]);}
export const getRoleLabel=(language:Language,value:ContactRole)=>roles[language][value];
export const getPropertyTypeLabel=(language:Language,value:PropertyType)=>propertyTypes[language][value];
export const getFurnishingLabel=(language:Language,value:Furnishing)=>furnishings[language][value];
export const getActivityLabel=(language:Language,value:ActivityType)=>activities[language][value];
type Value={language:Language;isRTL:boolean;t:(key:TranslationKey,values?:Record<string,string|number>)=>string;setLanguage:(value:Language)=>void};
const Context=createContext<Value|null>(null);const LANGUAGE_KEY='settings:language';
export function I18nProvider({children}:{children:React.ReactNode}){const [language,setLanguageState]=useState<Language>('ar');const [ready,setReady]=useState(false);
useEffect(()=>{void draftsRepository.load<Language>(LANGUAGE_KEY).then(saved=>{if(saved==='ar'||saved==='en')setLanguageState(saved)}).finally(()=>setReady(true))},[]);
const setLanguage=(value:Language)=>{setLanguageState(value);void draftsRepository.save(LANGUAGE_KEY,value)};
const value=useMemo<Value>(()=>({language,isRTL:language==='ar',t:(key,values)=>translate(language,key,values),setLanguage}),[language]);if(!ready)return null;return <Context.Provider value={value}>{children}</Context.Provider>;}
export function useI18n():Value{const value=useContext(Context);if(!value)throw new Error('I18nProvider missing');return value;}
