import {useCallback,useState,type ReactNode} from 'react';
import {Linking,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {router,useFocusEffect,useLocalSearchParams} from 'expo-router';
import {SafeAreaView} from 'react-native-safe-area-context';
import {AppHeader} from '@/components/AppHeader';
import {PrimaryButton} from '@/components/PrimaryButton';
import {contactsRepository,phoneRepository,propertiesRepository,requirementsRepository} from '@/lib/database';
import type {Contact,ContactPhone,Property,Requirement} from '@/types/domain';
import {colors,radius,spacing} from '@/theme/tokens';
import {getPropertyTypeLabel,getRoleLabel,useI18n} from '@/i18n/I18nContext';
import {callUri,orderedPhoneChoices} from '@/features/contacts/phoneActions';
import {WhatsAppChooser} from '@/components/WhatsAppChooser';

export default function ContactDetail(){const {id}=useLocalSearchParams<{id:string}>();const {t,language,isRTL}=useI18n();const [contact,setContact]=useState<Contact|null>(null);const [requirements,setRequirements]=useState<Requirement[]>([]);const [offered,setOffered]=useState<Property[]>([]);
  const [phones,setPhones]=useState<ContactPhone[]>([]);const [whatsAppPhone,setWhatsAppPhone]=useState<ContactPhone|null>(null);const load=useCallback(()=>{if(!id)return;void Promise.all([contactsRepository.get(id),phoneRepository.listForContact(id),requirementsRepository.forContact(id),propertiesRepository.forOfferedBy(id)]).then(([person,numbers,needs,properties])=>{setContact(person);setPhones(numbers);setRequirements(needs);setOffered(properties)})},[id]);
  useFocusEffect(useCallback(()=>{load()},[load]));if(!contact)return <SafeAreaView style={styles.page}><Text style={styles.loading}>{t('loading')}</Text></SafeAreaView>;
  const requirementSection=<Section title={t('requested')} hint={t('requestedHint')} action={t('addRequested')} isRTL={isRTL} onAction={()=>router.push({pathname:'/requirement-form',params:{contactId:contact.id}})}>
    {requirements.length?requirements.map(item=><RequirementCard key={item.id} item={item}/>):<Text style={styles.empty}>{t('noRequests')}</Text>}
  </Section>;
  const offeredSection=<Section title={t('offered')} hint={t('offeredHint')} action={t('addOffered')} isRTL={isRTL} onAction={()=>router.push({pathname:'/property-form',params:{offeredByContactId:contact.id}})}>
    {offered.length?offered.map(item=><Pressable key={item.id} onPress={()=>router.push({pathname:'/property-detail',params:{id:item.id}})} style={styles.card}>
      <Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.meta}>📍 {item.area}  •  {t('kwd',{value:item.monthlyRent})}</Text></Pressable>):<Text style={styles.empty}>{t('noOffered')}</Text>}
  </Section>;
  const requestedFirst=contact.role==='tenant';
  return <SafeAreaView style={styles.page} edges={['top']}><AppHeader title={t('personDetails')}/><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.person}><Text style={[styles.name,{textAlign:isRTL?'right':'left'}]}>{contact.name}</Text>{orderedPhoneChoices(phones).map(phone=><View key={phone.id} style={styles.phoneRow}>
      <View style={styles.phoneCopy}><Text style={[styles.phone,{textAlign:isRTL?'right':'left'}]}>{phone.display}</Text><Text style={[styles.phoneMeta,{textAlign:isRTL?'right':'left'}]}>{[phone.label,phone.isPrimary?t('primaryPhone'):null].filter(Boolean).join(' · ')}</Text></View>
      <View style={styles.phoneActions}><Pressable accessibilityLabel={`${t('call')} ${phone.display}`} onPress={()=>void Linking.openURL(callUri(phone))} style={styles.phoneAction}><Text style={styles.phoneActionText}>{t('call')}</Text></Pressable>
        <Pressable accessibilityLabel={`${t('whatsapp')} ${phone.display}`} onPress={()=>setWhatsAppPhone(phone)} style={styles.whatsappAction}><Text style={styles.whatsappText}>{t('whatsapp')}</Text></Pressable></View>
    </View>)}<Text style={[styles.badge,{alignSelf:isRTL?'flex-end':'flex-start'}]}>{getRoleLabel(language,contact.role)}</Text>
      {contact.notes?<Text style={[styles.notes,{textAlign:isRTL?'right':'left'}]}>{contact.notes}</Text>:null}<PrimaryButton title={t('editPersonData')} onPress={()=>router.push({pathname:'/contact-form',params:{id:contact.id}})}/></View>
    {requestedFirst?requirementSection:offeredSection}{requestedFirst?offeredSection:requirementSection}
  </ScrollView><WhatsAppChooser visible={whatsAppPhone!==null} message="" phone={whatsAppPhone?.normalized} onClose={()=>setWhatsAppPhone(null)}/></SafeAreaView>;
}

function RequirementCard({item}:{item:Requirement}){const {t,language}=useI18n();const rent=item.minRent!==null&&item.maxRent!==null?`${item.minRent}–${item.maxRent}`:t('flexibleBudget');
  return <View style={styles.card}><Text style={styles.cardTitle}>{item.propertyTypes.map(type=>getPropertyTypeLabel(language,type)).join('، ')||t('anyProperty')}</Text><Text style={styles.meta}>📍 {item.areas.join('، ')||t('anyArea')}</Text><Text style={styles.meta}>💰 {item.minRent!==null?t('kwd',{value:rent}):rent}{item.minBedrooms!==null?`  •  🛏️ ${item.minBedrooms}`:''}{item.minBathrooms!==null?`  •  🚿 ${item.minBathrooms}`:''}</Text>
    {item.notes?<Text style={styles.requirementNotes}>{item.notes}</Text>:null}<View style={styles.inlineActions}><Pressable onPress={()=>router.push({pathname:'/requirement-form',params:{id:item.id}})} style={styles.smallButton}><Text style={styles.smallText}>{t('edit')}</Text></Pressable><Pressable onPress={()=>router.push({pathname:'/match-results',params:{requirementId:item.id}})} style={[styles.smallButton,styles.matchButton]}><Text style={[styles.smallText,styles.matchText]}>{t('matchNow')}</Text></Pressable></View></View>;
}

function Section({title,hint,action,isRTL,onAction,children}:{title:string;hint:string;action:string;isRTL:boolean;onAction:()=>void;children:ReactNode}){return <View style={styles.section}><View style={[styles.sectionHeader,{flexDirection:isRTL?'row':'row-reverse'}]}><Pressable onPress={onAction}><Text style={styles.add}>{action}</Text></Pressable><View><Text style={[styles.sectionTitle,{textAlign:isRTL?'right':'left'}]}>{title}</Text><Text style={[styles.hint,{textAlign:isRTL?'right':'left'}]}>{hint}</Text></View></View>{children}</View>}

const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.background},loading:{textAlign:'center',marginTop:80,color:colors.muted},content:{padding:spacing.md,gap:spacing.lg,paddingBottom:spacing.xl},person:{gap:spacing.sm,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:spacing.md,backgroundColor:'white'},name:{fontSize:25,fontWeight:'800',textAlign:'right',color:colors.text},phoneRow:{gap:spacing.sm,borderTopWidth:1,borderTopColor:colors.border,paddingTop:spacing.sm},phoneCopy:{flex:1},phone:{fontSize:18,textAlign:'right',color:colors.blue},phoneMeta:{color:colors.muted,fontSize:12},phoneActions:{flexDirection:'row',gap:spacing.sm},phoneAction:{flex:1,minHeight:40,backgroundColor:colors.green,borderRadius:radius.sm,alignItems:'center',justifyContent:'center'},phoneActionText:{color:'white',fontWeight:'800'},whatsappAction:{flex:1,minHeight:40,backgroundColor:'#128C7E',borderRadius:radius.sm,alignItems:'center',justifyContent:'center'},whatsappText:{color:'white',fontWeight:'800'},badge:{alignSelf:'flex-end',color:colors.red,fontWeight:'800',backgroundColor:'#FFF1F1',paddingHorizontal:10,paddingVertical:5,borderRadius:radius.md},notes:{textAlign:'right',color:colors.text,lineHeight:22,backgroundColor:colors.surface,padding:spacing.sm,borderRadius:radius.sm},section:{gap:spacing.sm},sectionHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end',gap:spacing.md},sectionTitle:{fontSize:23,fontWeight:'900',color:colors.red,textAlign:'right'},hint:{fontSize:13,color:colors.muted,textAlign:'right',marginTop:3},add:{color:colors.blue,fontWeight:'800'},card:{gap:6,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:spacing.md,backgroundColor:'white'},cardTitle:{fontSize:17,fontWeight:'800',color:colors.text,textAlign:'right'},meta:{color:colors.muted,textAlign:'right',lineHeight:22},requirementNotes:{textAlign:'right',color:colors.text,backgroundColor:colors.surface,padding:spacing.sm,borderRadius:radius.sm},inlineActions:{flexDirection:'row',gap:spacing.sm,marginTop:spacing.xs},smallButton:{flex:1,minHeight:42,borderRadius:radius.sm,borderWidth:1,borderColor:colors.blue,alignItems:'center',justifyContent:'center'},matchButton:{backgroundColor:colors.blue},smallText:{color:colors.blue,fontWeight:'800'},matchText:{color:'white'},empty:{textAlign:'right',color:colors.muted,borderWidth:1,borderColor:colors.border,borderStyle:'dashed',borderRadius:radius.md,padding:spacing.md}});
