import {useEffect,useState} from 'react';import {Alert,Image,Linking,Platform,ScrollView,StyleSheet,Text,View} from 'react-native';import {router,useLocalSearchParams} from 'expo-router';
import * as FileSystem from 'expo-file-system/legacy';import * as IntentLauncher from 'expo-intent-launcher';
import {SafeAreaView} from 'react-native-safe-area-context';import {PrimaryButton} from '@/components/PrimaryButton';import {propertiesRepository} from '@/lib/database';
import {getActivityLabel,useI18n} from '@/i18n/I18nContext';
import {AppHeader} from '@/components/AppHeader';
import type {Property,PropertyMedia} from '@/types/domain';import {colors,radius,spacing} from '@/theme/tokens';
export default function PropertyDetail(){const {id,safe}=useLocalSearchParams<{id:string;safe?:string}>();const {t,language,isRTL}=useI18n();const [property,setProperty]=useState<Property|null>(null);const [media,setMedia]=useState<PropertyMedia[]>([]);const safeView=safe==='1';
  useEffect(()=>{if(id){propertiesRepository.get(id).then(setProperty);propertiesRepository.media(id).then(setMedia)}},[id]);if(!property)return <SafeAreaView><Text>{t('loading')}</Text></SafeAreaView>;
  const playVideo=async(uri:string)=>{try{if(Platform.OS==='android'){const data=uri.startsWith('file:')?await FileSystem.getContentUriAsync(uri):uri;await IntentLauncher.startActivityAsync('android.intent.action.VIEW',{data,type:'video/*',flags:1})}else await Linking.openURL(uri)}catch{Alert.alert(t('videoOpenFailed'),t('videoOpenFailedMessage'))}};
  const aligned={textAlign:isRTL?'right' as const:'left' as const};
  return <SafeAreaView style={styles.page} edges={['top']}><AppHeader title={safeView?t('propertyPreview'):t('propertyDetails')}/><ScrollView contentContainerStyle={styles.content}>{safeView?<Text style={[styles.safeBanner,aligned]}>{t('safeMode')}</Text>:null}<Text style={[styles.title,aligned]}>{property.title}</Text><Text style={[styles.price,aligned]}>{t('monthlyKwd',{value:property.monthlyRent})}</Text>
    <Text style={[styles.line,aligned]}>📍 {property.area}</Text>{property.blockNumber!==null&&<Text style={[styles.line,aligned]}>🏘️ {t('blockNumberValue',{value:property.blockNumber})}</Text>}{property.bedrooms!==null&&<Text style={[styles.line,aligned]}>🛏️ {t('rooms',{value:property.bedrooms})}</Text>}{property.bathrooms!==null&&<Text style={[styles.line,aligned]}>🚿 {t('baths',{value:property.bathrooms})}</Text>}
    {property.paciNumberCount!==null&&<Text style={[styles.line,aligned]}>🔢 {t('paciNumbers',{value:property.paciNumberCount})}</Text>}{property.activityType&&<Text style={[styles.line,aligned]}>💼 {getActivityLabel(language,property.activityType)}</Text>}
    {property.description?<Text style={styles.description}>{property.description}</Text>:null}<ScrollView horizontal contentContainerStyle={styles.media}>{media.filter(x=>x.kind==='image').map(x=><Image key={x.id} source={{uri:x.uri}} style={styles.image}/>)}</ScrollView>
    {media.filter(x=>x.kind==='video').map((video,index)=><PrimaryButton key={video.id} title={t('playVideo',{number:index+1})} onPress={()=>void playVideo(video.uri)} color={colors.green}/>)}
    <PrimaryButton title={t('shareWhatsapp')} onPress={()=>router.push({pathname:'/share-property',params:{id:property.id}})} color={colors.green}/><PrimaryButton title={t('matchingSeekers')} onPress={()=>router.push({pathname:'/match-results',params:{propertyId:property.id}})}/>{!safeView?<PrimaryButton title={t('editProperty')} onPress={()=>router.push({pathname:'/property-form',params:{id:property.id}})}/>:null}
    {!safeView&&property.privateNotes?<View style={styles.private}><Text style={[styles.privateTitle,aligned]}>{t('privateDoNotShare')}</Text><Text style={aligned}>{property.privateNotes}</Text></View>:null}</ScrollView></SafeAreaView>}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.background},content:{padding:spacing.md,gap:spacing.md},title:{fontSize:26,fontWeight:'700',color:colors.red,textAlign:'right'},price:{fontSize:22,fontWeight:'700',color:colors.blue,textAlign:'right'},
  line:{fontSize:17,textAlign:'right'},description:{fontSize:16,lineHeight:25,textAlign:'right'},media:{gap:spacing.sm},image:{width:230,height:160,borderRadius:radius.md},private:{backgroundColor:colors.surface,padding:spacing.md,borderRadius:radius.md},
  privateTitle:{color:colors.red,fontWeight:'700',textAlign:'right',marginBottom:spacing.sm},safeBanner:{backgroundColor:'#EBF8EF',color:colors.text,textAlign:'right',padding:spacing.md,borderRadius:radius.md,fontWeight:'700'}});
