import {useEffect,useState} from 'react';import {Image,ScrollView,StyleSheet,Text,View} from 'react-native';import {router,useLocalSearchParams} from 'expo-router';
import {SafeAreaView} from 'react-native-safe-area-context';import {PrimaryButton} from '@/components/PrimaryButton';import {propertiesRepository} from '@/lib/database';
import {activityLabel} from '@/features/properties/propertyFields';
import {AppHeader} from '@/components/AppHeader';
import type {Property,PropertyMedia} from '@/types/domain';import {colors,radius,spacing} from '@/theme/tokens';
export default function PropertyDetail(){const {id,safe}=useLocalSearchParams<{id:string;safe?:string}>();const [property,setProperty]=useState<Property|null>(null);const [media,setMedia]=useState<PropertyMedia[]>([]);const safeView=safe==='1';
  useEffect(()=>{if(id){propertiesRepository.get(id).then(setProperty);propertiesRepository.media(id).then(setMedia)}},[id]);if(!property)return <SafeAreaView><Text>جارٍ التحميل...</Text></SafeAreaView>;
  return <SafeAreaView style={styles.page} edges={['top']}><AppHeader title={safeView?'معاينة العقار':'تفاصيل العقار'}/><ScrollView contentContainerStyle={styles.content}>{safeView?<Text style={styles.safeBanner}>🔒 وضع آمن: الملاحظات الخاصة ومصدر العرض مخفيان.</Text>:null}<Text style={styles.title}>{property.title}</Text><Text style={styles.price}>{property.monthlyRent} د.ك شهريًا</Text>
    <Text style={styles.line}>📍 {property.area}</Text>{property.bedrooms!==null&&<Text style={styles.line}>🛏️ {property.bedrooms} غرف</Text>}{property.bathrooms!==null&&<Text style={styles.line}>🚿 {property.bathrooms} حمام</Text>}
    {property.paciNumberCount!==null&&<Text style={styles.line}>🔢 {property.paciNumberCount} أرقام آلية</Text>}{property.activityType&&<Text style={styles.line}>💼 {activityLabel(property.activityType)}</Text>}
    {property.description?<Text style={styles.description}>{property.description}</Text>:null}<ScrollView horizontal contentContainerStyle={styles.media}>{media.filter(x=>x.kind==='image').map(x=><Image key={x.id} source={{uri:x.uri}} style={styles.image}/>)}</ScrollView>
    <PrimaryButton title="معاينة ثم مشاركة إلى WhatsApp" onPress={()=>router.push({pathname:'/share-property',params:{id:property.id}})} color={colors.green}/><PrimaryButton title="الباحثون المطابقون" onPress={()=>router.push({pathname:'/match-results',params:{propertyId:property.id}})}/>{!safeView?<PrimaryButton title="تعديل العقار" onPress={()=>router.push({pathname:'/property-form',params:{id:property.id}})}/>:null}
    {!safeView&&property.privateNotes?<View style={styles.private}><Text style={styles.privateTitle}>ملاحظات خاصة — لا تُشارك</Text><Text>{property.privateNotes}</Text></View>:null}</ScrollView></SafeAreaView>}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.background},content:{padding:spacing.md,gap:spacing.md},title:{fontSize:26,fontWeight:'700',color:colors.red,textAlign:'right'},price:{fontSize:22,fontWeight:'700',color:colors.blue,textAlign:'right'},
  line:{fontSize:17,textAlign:'right'},description:{fontSize:16,lineHeight:25,textAlign:'right'},media:{gap:spacing.sm},image:{width:230,height:160,borderRadius:radius.md},private:{backgroundColor:colors.surface,padding:spacing.md,borderRadius:radius.md},
  privateTitle:{color:colors.red,fontWeight:'700',textAlign:'right',marginBottom:spacing.sm},safeBanner:{backgroundColor:'#EBF8EF',color:colors.text,textAlign:'right',padding:spacing.md,borderRadius:radius.md,fontWeight:'700'}});
