import {Ionicons} from '@expo/vector-icons';
import {router,useFocusEffect} from 'expo-router';
import {useCallback,useState} from 'react';
import {Pressable,StyleSheet,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {AppHeader} from '@/components/AppHeader';
import {useI18n} from '@/i18n/I18nContext';
import {propertiesRepository,quickCapturesRepository,requirementsRepository} from '@/lib/database';
import {colors,radius,spacing} from '@/theme/tokens';
export default function Home(){const {t,isRTL}=useI18n();const [counts,setCounts]=useState({requirements:0,properties:0,drafts:0});
  useFocusEffect(useCallback(()=>{void Promise.all([requirementsRepository.listActive(),propertiesRepository.list(),quickCapturesRepository.list()]).then(([requirements,properties,drafts])=>setCounts({requirements:requirements.length,properties:properties.length,drafts:drafts.length}))},[]));
  return <SafeAreaView style={styles.page} edges={['top']}>
  <AppHeader title="ViewState Lite"/>
  <View style={styles.content}><View style={[styles.hero,{flexDirection:isRTL?'row-reverse':'row'}]}><View style={styles.heroCopy}><Text style={[styles.kicker,{textAlign:isRTL?'right':'left'}]}>LITE-03</Text><Text style={[styles.welcome,{textAlign:isRTL?'right':'left'}]}>{t('homeGreeting')}</Text></View><View style={styles.mark}><Text style={styles.markText}>V</Text></View></View>
    <ActionCard isRTL={isRTL} title={t('importWhatsApp')} description={t('importWhatsAppHint')} icon="logo-whatsapp" color={colors.green} soft="#EBF8EF" onPress={()=>router.push('/whatsapp-import')}/>
    <ActionCard isRTL={isRTL} title={t('quickCapture')} description={t('quickCaptureHint')} icon="flash" color="#C67B00" soft="#FFF8E1" onPress={()=>router.push('/quick-capture')}/>
    <View style={[styles.miniGrid,{flexDirection:isRTL?'row-reverse':'row'}]}><MiniCard isRTL={isRTL} title={t('addContact')} icon="person-add-outline" onPress={()=>router.push('/contact-add')}/><MiniCard isRTL={isRTL} title={t('addProperty')} icon="business-outline" onPress={()=>router.push('/property-form')}/></View>
    <Text style={[styles.sectionTitle,{textAlign:isRTL?'right':'left'}]}>{t('home')}</Text><View style={[styles.stats,{flexDirection:isRTL?'row-reverse':'row'}]}><Stat value={counts.requirements} label={t('activeRequests')}/><Stat value={counts.properties} label={t('availableProperties')}/><Pressable onPress={()=>router.push('/quick-capture')} style={styles.stat}><Text style={styles.statValue}>{counts.drafts}</Text><Text style={styles.statLabel}>{t('drafts')}</Text></Pressable></View>
  </View></SafeAreaView>}
function ActionCard({title,description,icon,color,soft,onPress,isRTL}:{title:string;description:string;icon:any;color:string;soft:string;onPress:()=>void;isRTL:boolean}){return <Pressable onPress={onPress} style={({pressed})=>[styles.action,{opacity:pressed?.8:1,flexDirection:isRTL?'row-reverse':'row'}]}><View style={[styles.actionIcon,{backgroundColor:soft}]}><Ionicons name={icon} size={27} color={color}/></View><View style={styles.actionCopy}><Text style={[styles.actionTitle,{textAlign:isRTL?'right':'left'}]}>{title}</Text><Text style={[styles.actionDescription,{textAlign:isRTL?'right':'left'}]}>{description}</Text></View><Ionicons name={isRTL?'chevron-back':'chevron-forward'} size={20} color={colors.muted}/></Pressable>}
function MiniCard({title,icon,onPress,isRTL}:{title:string;icon:any;onPress:()=>void;isRTL:boolean}){return <Pressable onPress={onPress} style={[styles.mini,{flexDirection:isRTL?'row-reverse':'row'}]}><View style={styles.miniIcon}><Ionicons name={icon} size={22} color={colors.blue}/></View><Text style={[styles.miniText,{textAlign:isRTL?'right':'left'}]}>{title}</Text></Pressable>}
function Stat({value,label}:{value:number;label:string}){return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.background},content:{padding:spacing.md,gap:spacing.sm},hero:{minHeight:122,backgroundColor:'#EEF5FF',borderWidth:1,borderColor:'#D4E5F8',borderRadius:radius.lg,padding:spacing.md,flexDirection:'row-reverse',alignItems:'center',justifyContent:'space-between',marginBottom:spacing.sm},heroCopy:{flex:1},kicker:{fontSize:12,fontWeight:'900',color:colors.red},welcome:{fontSize:20,lineHeight:31,color:colors.text,fontWeight:'800',marginTop:spacing.xs},mark:{width:55,height:55,borderRadius:18,backgroundColor:colors.blue,alignItems:'center',justifyContent:'center',shadowColor:colors.blue,shadowOpacity:.25,shadowRadius:10,elevation:5},markText:{fontSize:31,fontFamily:'serif',fontWeight:'900',color:'white'},
  action:{minHeight:78,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,backgroundColor:'white',padding:spacing.sm,flexDirection:'row-reverse',alignItems:'center',gap:spacing.md,elevation:1},actionIcon:{width:50,height:50,borderRadius:16,alignItems:'center',justifyContent:'center'},actionCopy:{flex:1},actionTitle:{fontSize:16,fontWeight:'900',textAlign:'right',color:colors.text},actionDescription:{fontSize:12,color:colors.muted,textAlign:'right',marginTop:4},miniGrid:{gap:spacing.sm,marginTop:spacing.xs},mini:{flex:1,minHeight:58,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:'white',padding:spacing.sm,flexDirection:'row-reverse',alignItems:'center',gap:spacing.sm},miniIcon:{width:35,height:35,borderRadius:11,backgroundColor:'#EEF5FF',alignItems:'center',justifyContent:'center'},miniText:{fontSize:13,fontWeight:'800',flex:1,textAlign:'right'},sectionTitle:{fontSize:16,fontWeight:'900',marginTop:spacing.md},stats:{gap:spacing.sm},stat:{flex:1,minHeight:78,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,alignItems:'center',justifyContent:'center',padding:spacing.xs,backgroundColor:'white'},statValue:{fontSize:23,fontWeight:'900',color:colors.blue},statLabel:{fontSize:10,color:colors.muted,textAlign:'center',marginTop:3}});
