import {Alert,Pressable,StyleSheet,Text,View} from 'react-native';import {SafeAreaView} from 'react-native-safe-area-context';import {AppHeader} from '@/components/AppHeader';import {PrimaryButton} from '@/components/PrimaryButton';
import {createAndShareBackup,pickAndRestoreBackup} from '@/features/sharing/backup';import {useI18n} from '@/i18n/I18nContext';import {colors,radius,spacing} from '@/theme/tokens';
export default function MoreScreen(){const {t,language,isRTL,setLanguage}=useI18n();const createBackup=async()=>{try{await createAndShareBackup()}catch{Alert.alert(t('backupFailed'),t('tryAgain'))}};
  const backup=()=>Alert.alert(t('backupWarningTitle'),t('backupWarning'),[{text:t('cancel'),style:'cancel'},{text:t('continueBackup'),onPress:()=>void createBackup()}]);
  return <SafeAreaView style={styles.page} edges={['top']}><AppHeader title={t('more')}/><View style={styles.content}><Text style={styles.section}>{t('language')}</Text><View style={styles.languages}>
    <Pressable onPress={()=>setLanguage('ar')} style={[styles.choice,language==='ar'&&styles.active]}><Text style={language==='ar'&&styles.activeText}>العربية</Text></Pressable>
    <Pressable onPress={()=>setLanguage('en')} style={[styles.choice,language==='en'&&styles.active]}><Text style={language==='en'&&styles.activeText}>English</Text></Pressable></View>
    <Text style={[styles.section,{textAlign:isRTL?'right':'left'}]}>{t('dataProtection')}</Text><PrimaryButton title={t('backupCreate')} onPress={backup}/><PrimaryButton title={t('backupRestore')} onPress={async()=>{try{await pickAndRestoreBackup();Alert.alert(t('restoreDone'),t('restoreDoneMessage'))}catch{Alert.alert(t('restoreFailed'),t('restoreFailedMessage'))}}}/><View style={styles.info}><Text style={[styles.infoTitle,{textAlign:isRTL?'right':'left'}]}>ViewState Lite App Icon Update · V0.5.6</Text>
      <Text style={[styles.infoText,{textAlign:isRTL?'right':'left'}]}>{t('privacyInfo')}</Text></View></View></SafeAreaView>}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.background},content:{padding:spacing.md,gap:spacing.md},section:{fontSize:18,fontWeight:'700',color:colors.red,textAlign:'right'},languages:{flexDirection:'row-reverse',gap:spacing.sm},choice:{borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:spacing.md},active:{backgroundColor:colors.blue},activeText:{color:'white',fontWeight:'700'},
  info:{backgroundColor:colors.surface,borderRadius:radius.md,padding:spacing.md,marginTop:spacing.lg},infoTitle:{fontWeight:'700',fontSize:17,textAlign:'right'},infoText:{color:colors.muted,lineHeight:24,textAlign:'right',marginTop:spacing.sm}});
