import {Alert,Pressable,StyleSheet,Text,View} from 'react-native';import {SafeAreaView} from 'react-native-safe-area-context';import {AppHeader} from '@/components/AppHeader';import {PrimaryButton} from '@/components/PrimaryButton';
import {createAndShareBackup,pickAndRestoreBackup} from '@/features/sharing/backup';import {useI18n} from '@/i18n/I18nContext';import {colors,radius,spacing} from '@/theme/tokens';
export default function MoreScreen(){const {t,language,setLanguage,isRTL}=useI18n();const backup=async()=>{try{await createAndShareBackup(language==='ar'?'حفظ نسخة ViewState Lite الاحتياطية':'Save ViewState Lite backup')}catch{Alert.alert(language==='ar'?'تعذر إنشاء النسخة':'Could not create backup',language==='ar'?'حاول مرة أخرى.':'Please try again.')}};
  return <SafeAreaView style={styles.page} edges={['top']}><AppHeader title={t('more')}/><View style={styles.content}><Text style={[styles.section,{textAlign:isRTL?'right':'left'}]}>{t('language')}</Text><View style={[styles.languages,{flexDirection:isRTL?'row-reverse':'row'}]}>
    <Pressable onPress={()=>setLanguage('ar')} style={[styles.choice,language==='ar'&&styles.active]}><Text style={language==='ar'&&styles.activeText}>العربية</Text></Pressable>
    <Pressable onPress={()=>setLanguage('en')} style={[styles.choice,language==='en'&&styles.active]}><Text style={language==='en'&&styles.activeText}>English</Text></Pressable></View>
    <Text style={[styles.section,{textAlign:isRTL?'right':'left'}]}>{t('dataProtection')}</Text><Text style={[styles.protection,{textAlign:isRTL?'right':'left'}]}>{t('dataProtectionHint')}</Text>
    <PrimaryButton title={t('createBackup')} onPress={backup}/><PrimaryButton title={t('restoreBackup')} onPress={async()=>{try{await pickAndRestoreBackup();Alert.alert(language==='ar'?'تمت الاستعادة':'Restore complete',language==='ar'?'تم دمج البيانات الموجودة في النسخة بأمان.':'Backup data was merged safely.')}catch{Alert.alert(language==='ar'?'تعذرت الاستعادة':'Restore failed',language==='ar'?'الملف غير صالح أو غير متوافق.':'The file is invalid or incompatible.')}}}/><View style={styles.info}><Text style={[styles.infoTitle,{textAlign:isRTL?'right':'left'}]}>{t('versionLabel')}</Text>
      <Text style={[styles.infoText,{textAlign:isRTL?'right':'left'}]}>{t('localOnlyInfo')}</Text></View></View></SafeAreaView>}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.background},content:{padding:spacing.md,gap:spacing.md},section:{fontSize:18,fontWeight:'700',color:colors.red,textAlign:'right'},languages:{flexDirection:'row-reverse',gap:spacing.sm},choice:{borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:spacing.md},active:{backgroundColor:colors.blue},activeText:{color:'white',fontWeight:'700'},
  protection:{color:colors.muted,lineHeight:22,marginTop:-spacing.sm},info:{backgroundColor:colors.surface,borderRadius:radius.md,padding:spacing.md,marginTop:spacing.lg},infoTitle:{fontWeight:'700',fontSize:17},infoText:{color:colors.muted,lineHeight:24,marginTop:spacing.sm}});
