import {Alert,Pressable,StyleSheet,Text,View} from 'react-native';import {SafeAreaView} from 'react-native-safe-area-context';import {AppHeader} from '@/components/AppHeader';import {PrimaryButton} from '@/components/PrimaryButton';
import {createAndShareBackup,pickAndRestoreBackup} from '@/features/sharing/backup';import {useI18n} from '@/i18n/I18nContext';import {colors,radius,spacing} from '@/theme/tokens';
export default function MoreScreen(){const {t,language,setLanguage}=useI18n();const backup=async()=>{try{await createAndShareBackup()}catch{Alert.alert('تعذر إنشاء النسخة','حاول مرة أخرى.')}};
  return <SafeAreaView style={styles.page} edges={['top']}><AppHeader title={t('more')}/><View style={styles.content}><Text style={styles.section}>{t('language')}</Text><View style={styles.languages}>
    <Pressable onPress={()=>setLanguage('ar')} style={[styles.choice,language==='ar'&&styles.active]}><Text style={language==='ar'&&styles.activeText}>العربية</Text></Pressable>
    <Pressable onPress={()=>setLanguage('en')} style={[styles.choice,language==='en'&&styles.active]}><Text style={language==='en'&&styles.activeText}>English</Text></Pressable></View>
    <Text style={styles.section}>حماية البيانات</Text><PrimaryButton title="إنشاء ومشاركة نسخة احتياطية" onPress={backup}/><PrimaryButton title="استعادة نسخة احتياطية" onPress={async()=>{try{await pickAndRestoreBackup();Alert.alert('تمت الاستعادة','تم دمج البيانات الموجودة في النسخة بأمان.')}catch{Alert.alert('تعذرت الاستعادة','الملف غير صالح أو غير متوافق.')}}}/><View style={styles.info}><Text style={styles.infoTitle}>ViewState Lite V0.1</Text>
      <Text style={styles.infoText}>بياناتك محفوظة محليًا على هاتفك ولا تتم مشاركتها إلا باختيارك. النسخة الحالية تحفظ السجلات النصية؛ احتفظ بنسخة مستقلة من الصور والفيديوهات المهمة حتى تكتمل حزمة النسخ الاحتياطي للوسائط.</Text></View></View></SafeAreaView>}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.background},content:{padding:spacing.md,gap:spacing.md},section:{fontSize:18,fontWeight:'700',color:colors.red,textAlign:'right'},languages:{flexDirection:'row-reverse',gap:spacing.sm},choice:{borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:spacing.md},active:{backgroundColor:colors.blue},activeText:{color:'white',fontWeight:'700'},
  info:{backgroundColor:colors.surface,borderRadius:radius.md,padding:spacing.md,marginTop:spacing.lg},infoTitle:{fontWeight:'700',fontSize:17,textAlign:'right'},infoText:{color:colors.muted,lineHeight:24,textAlign:'right',marginTop:spacing.sm}});
