import {Pressable,StyleSheet,Text,View} from 'react-native';
import type {MatchResult,Property,Requirement} from '@/types/domain';
import {colors,radius,spacing} from '@/theme/tokens';
import {useI18n} from '@/i18n/I18nContext';

export function MatchCard({match,property,requirement,contactName,onPressProperty,onPressContact}:{match:MatchResult;property:Property;requirement:Requirement;contactName:string;onPressProperty?:()=>void;onPressContact?:()=>void}){
  const {t,isRTL}=useI18n();const aligned={textAlign:isRTL?'right' as const:'left' as const};
  const evaluated=match.criteria.filter(item=>item.state!=='not_specified');
  return <View style={styles.card}><View style={[styles.top,{flexDirection:isRTL?'row-reverse':'row'}]}><View style={styles.copy}><Pressable disabled={!onPressContact} onPress={onPressContact}><Text style={[styles.person,aligned]}>{contactName}</Text></Pressable><Pressable disabled={!onPressProperty} onPress={onPressProperty}><Text style={[styles.property,aligned]}>{property.title}</Text></Pressable><Text style={[styles.summary,aligned]}>📍 {property.area}  •  💰 {t('kwd',{value:property.monthlyRent})}</Text></View><View style={styles.score}><Text style={styles.scoreNumber}>{match.score}%</Text><Text style={styles.scoreLabel}>{t('match')}</Text></View></View>
    <View style={styles.criteria}>{evaluated.map(item=><View key={item.field} style={[styles.criterion,{flexDirection:isRTL?'row-reverse':'row'},item.state==='matched'?styles.good:item.state==='partial'?styles.partial:styles.missed]}><Text style={styles.icon}>{item.state==='matched'?'✓':item.state==='partial'?'≈':'!'}</Text><View style={styles.criterionCopy}><Text style={[styles.criterionLabel,aligned]}>{item.label} · {item.earned}/{item.weight}</Text><Text style={[styles.explanation,aligned]}>{item.explanation}</Text></View></View>)}</View>
    {requirement.notes?<Text style={[styles.note,aligned]}>{t('requirementNote',{note:requirement.notes})}</Text>:null}
  </View>;
}

const styles=StyleSheet.create({card:{borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:spacing.md,gap:spacing.md,backgroundColor:'white'},top:{flexDirection:'row-reverse',alignItems:'center',gap:spacing.md},copy:{flex:1},person:{fontSize:15,fontWeight:'800',color:colors.blue,textAlign:'right'},property:{fontSize:18,fontWeight:'900',color:colors.text,textAlign:'right',marginTop:4},summary:{color:colors.muted,textAlign:'right',marginTop:6},score:{width:70,height:70,borderRadius:35,backgroundColor:'#EAF4FF',alignItems:'center',justifyContent:'center',borderWidth:2,borderColor:colors.blue},scoreNumber:{fontSize:20,fontWeight:'900',color:colors.blue},scoreLabel:{fontSize:11,color:colors.muted},criteria:{gap:spacing.xs},criterion:{flexDirection:'row-reverse',alignItems:'center',gap:spacing.sm,borderRadius:radius.sm,padding:spacing.sm},good:{backgroundColor:'#EBF8EF'},partial:{backgroundColor:'#FFF7E1'},missed:{backgroundColor:'#FFF0F0'},icon:{width:24,textAlign:'center',fontWeight:'900',color:colors.text},criterionCopy:{flex:1},criterionLabel:{fontWeight:'800',textAlign:'right',color:colors.text},explanation:{fontSize:13,color:colors.muted,textAlign:'right',marginTop:2},note:{textAlign:'right',color:colors.text,backgroundColor:colors.surface,padding:spacing.sm,borderRadius:radius.sm}});
